config/routes.rb
Affordable::Application.routes.draw do
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  root :to=> 'visitors#new'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_no_table

  column :firstname, :string
  column :lastname, :string
  column :email, :string
  column :content, :string

  validates_presence_of :firstname
  validates_presence_of :lastname
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500

  def update_spreadsheet
    connection = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"])
    ss = connection.spreadsheet_by_title('Learn-Rails-Example')
    if ss.nil?
      ss = connection.create_spreadsheet('Learn-Rails-Example')
    end
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.new
    ws[last_row, 2] = self.name
    ws[last_row, 3] = self.email
    ws[last_row, 4] = self.content
    ws.save
  end

  def name
    [firstname, lastname].join " "
  end

  def self.by_letter(letter)
    where("lastname LIKE ?", "#{letter}%").order(:lastname)
  end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_no_table
  column :email, :string
  validates_presence_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon::API.new
    result = mailchimp.lists.subscribe({
      :id => ENV['MAILCHIMP_LIST_ID'],
      :email => {:email => self.email},
      :double_optin => false,
      :update_existing => true,
      :send_welcome => true
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      @contact.update_spreadsheet
      UserMailer.contact_email(@contact).deliver
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:contact).permit(:firstname, :lastname, :email, :content)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Signed up #{@visitor.email}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:visitor).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3>
<div class="form">
  <%= simple_form_for @contact do |form| %>
    <%= form.error_notification %>
    <%= form.input :firstname, autofocus: true %>
    <%= form.input :lastname, autofocus: true %>
    <%= form.input :email %>
    <%= form.input :content, as: :text %>
    <%= form.button :submit, 'Submit', class: 'submit' %>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
    <div id="navbar-main">
      <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon icon-shield" style="font-size:30px; color:#3498db;"></span>
          </button>
          <a class="navbar-brand hidden-xs hidden-sm" href="#home"><span class="icon icon-shield" style="font-size:18px; color:#3498db;"></span></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="#home" class="smoothScroll">Home</a></li>
      <li> <a href="#about" class="smoothScroll"> About</a></li>
      <li> <a href="#services" class="smoothScroll"> Services</a></li>
      <li> <a href="#team" class="smoothScroll"> Team</a></li>
      <li> <a href="#contact" class="smoothScroll"> Contact</a></li>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    </div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Affordable" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Affordable" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body data-spy="scroll" data-offset="0" data-target="#navbar-main">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    
  <script type="text/javascript" src="assets/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="assets/js/retina.js"></script>
  <script type="text/javascript" src="assets/js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="assets/js/smoothscroll.js"></script>
  <script type="text/javascript" src="assets/js/jquery-func.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
 
 
 
<!-- Section 1 -->
	<section id="intro" data-speed="6" data-type="background">
		<div class="container">
			<div class="row-fluid">
		        <div class="span4 text-center">
		          <img src="images/desktop.png">
		        </div>
		        <div class="span8 text-center">
		          <img src="../title.png">
		        </div>
	    	</div>
	    	<div class="hero-unit">
	    		<h2>This page demonstrates parallax within Twitter Bootstrap.</h2>
	    		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	    		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	    		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	    		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	    		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	    		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	    	</div>
	    </div>
	</section>
<!-- Section #2 -->
	<section id="home" data-speed="6" data-type="background">
		<div class="container">
			<div class="row-fluid">
		        <div class="span4 well">
		          <h2>Heading</h2>
		          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque cursus nisl consectetur et.</p>
		          <p><a class="btn btn-success" href="#">View details &raquo;</a></p>
		        </div><!-- /.span4 -->
		        <div class="span4 well">
		          <h2>Heading</h2>
		          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
		          <p><a class="btn btn-success" href="#">View details &raquo;</a></p>
		        </div><!-- /.span4 -->
		        <div class="span4 well">
		          <h2>Heading</h2>
		          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum odio, dapibus ac in, massa justo sit amet.</p>
		          <p><a class="btn btn-success" href="#">View details &raquo;</a></p>
		        </div><!-- /.span4 -->
	    	</div>
	    </div>
	</section>
<!-- Section #3 -->
	<section id="about" data-speed="2" data-type="background">
		<div class="container">
			<div class="page-header">
				<h1>Final Section Headline <small>Some subtext goes here...</small></h1>
			</div>
			<div class="row-fluid">
		        <div class="span4">
		          <h2>More Details</h2>
		          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque cursus nisl consectetur et.</p>
		          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque cursus nisl consectetur et.</p>
		          <p><a class="btn btn-success">View details &raquo;</a></p>
		        </div><!-- /.span4 -->
		        <div class="span4">
		         	<h2>Heading</h2>
		         	<div class="media">
						<a class="pull-left" href="#">
					    	<img class="media-object" src="images/check.png">
						</a>
						<div class="media-body">
						    <h4 class="media-heading">Media heading</h4>
						    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante.
						</div>
					</div>
		         	<div class="media">
						<a class="pull-left" href="#">
					    	<img class="media-object" src="images/check.png">
						</a>
						<div class="media-body">
						    <h4 class="media-heading">Media heading</h4>
						    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante.
						</div>
					</div>
		         	<div class="media">
						<a class="pull-left" href="#">
					    	<img class="media-object" src="images/check.png">
						</a>
						<div class="media-body">
						    <h4 class="media-heading">Media heading</h4>
						    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante.
						</div>
					</div>
		        </div><!-- /.span4 -->
		        <div class="span4">
		          <h2>Log In</h2>
		          <form class="form">
					  
					  <div class="control-group">
					    <label class="control-label" for="inputEmail">Email</label>
					    <div class="controls">
					      <input type="text" id="inputEmail" placeholder="Email">
					    </div>
					  </div>
					  
					  <div class="control-group">
					    <label class="control-label" for="inputPassword">Password</label>
					    <div class="controls">
					      <input type="password" id="inputPassword" placeholder="Password">
					    </div>
					  </div>
					  <div class="control-group">
					    <div class="controls">
					      <label class="checkbox">
					        <input type="checkbox"> Remember me <br><br>
					      </label>
					      <button type="submit" class="btn btn-success">Sign in</button>
					    </div>
					  </div>
					</form>
		        </div><!-- /.span4 -->
	    	</div>
	    </div>
	</section>

app/views/visitors/new.html.erb
<% content_for :title do %>Foobar Kadigan<% end %>
<% content_for :description do %>Website of Foobar Kadigan<% end %>

<!-- ######################## Header ######################## -->
        
<div id="headerwrap" id="home" name="home">
  <header class="clearfix">
    <h1><span class="icon icon-shield"></span></h1>
      <p>Events In Your Life Sometimes Happen Spontaneously.</p>
      <p>So Should You.</p>
  </header>     
</div><!-- /headerwrap -->

    
    <!-- ==== ABOUT ==== -->
    <div class="container" id="about" name="about">
      <div class="row white">
      <br>
        <h1 class="centered">WE ARE CHANGING HOW YOU DEAL WITH THE UNEXPECTED FREE...</h1>
        <hr>
        
        <div class="col-lg-6">
          <p>Through our day to day lives we get caught up in the hustle and bustle of the world. With school, work, sports, kids, and everything else life throws at us, we get pressed for the activities that we truely enjoy. spontaneity has lost its wonder as it was when we were younger and we live like robots on auto-pilot living the same mundane routines day in and day out. Though life does give us our glimpse's of unplanned downtime, we're often stuck trying to quickly form a plan on what to do and who to see. We spring to type our group messages, but waste time going through our contacts one by one searching for the right group of people we want to see our messages. </p>
        </div><!-- col-lg-6 -->
        
        <div class="col-lg-6">
          <p>This is our solution, a single place to form your groups, and to save them as queries so when life gives you the unexpected curve ball, you are prepared to greet it with the bat of your greatness, and effeciently plan to do what your inner youth truely wants to. With todays technology you should be more inclined to be personable, getting out with your friends should be simple, and with the current methods of messaging and group forming, it doesn't complete the task. </p>
        </div><!-- col-lg-6 -->
      </div><!-- row -->
    </div><!-- container -->
    
    <!-- ==== SECTION DIVIDER1 -->
    <section class="section-divider textdivider divider1">
      <div class="container">
        <h1>SIMPLE, SWEET, AND HARD TO BEAT.</h1>
        <hr>
        <p>Messaging your friends to hang out should be quick, and efficient. who wants to be bugged by group messaging if they can't be a part of the fun? </p>
      </div><!-- container -->
    </section><!-- section -->
    
    
    <!-- ==== SERVICES ==== -->
    <div class="container" id="services" name="services">
      <br>
      <br>
      <div class="row">
        <h2 class="centered">YOUR GROUPS, ONE APP, MANY MEMORIES</h2>
        <hr>
        <br>
        <div class="col-lg-offset-2 col-lg-8">
          <p>When your are out and about, you develop several different groups of friends. You may be at a party, or a concert, or at work. All these places hav a different group that you associate with, so why not group them together in one place? With LinkUp you can, and that's beautiful. you can organize your groups based off of the things you share in common with each member so you can later come back to that group and invite them out when you want to share memories with them.</p>
          <p></p>
          <p></p>
        </div><!-- col-lg -->
      </div><!-- row -->
      
      <div class="row">
        <h2 class="centered"><!-- MOBILE FIRST THINKING, ALWAYS. --></h2>
        <hr>
        <br>
        <div class="col-lg-offset-2 col-lg-8">
          <img class="img-responsive" src="assets/img/iphone.png" alt="">
        </div><!-- col -->
      </div><!-- row -->
    </div><!-- container -->
      

    <!-- ==== SECTION DIVIDER2 -->
    <section class="section-divider textdivider divider2">
      <div class="container">
        <h1>MAGICAL DISAPPEARING ACT</h1>
        <hr>
        <p>Timing is everything when you live the busy life, and it's key to catch the opportunities when they happen. But one of the worst things to see is when you miss those opportunities.</p>
      </div><!-- container -->
    </section><!-- section -->


    <!-- ==== GREYWRAP ==== -->
    <div id="greywrap">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 centered">
            <img class="img-responsive" src="assets/img/macbook.png" align="">
          </div>
          <div class="col-lg-4">
            <h2>Quaries that expire</h2>
            <p>Our message quaries expire after designated time periods. This means that when you are busy, you won't be inturupted continuously of your friends that are out having fun. This also means that you wouldn't be requested by your fellows that were unfortunate enough to miss your request to see them, therefore no party gets hurt feelings.</p>
          </div>          
        </div><!-- row -->
      </div>
      <br>
      <br>
    </div><!-- greywrap -->
    
   
    <!-- ==== SECTION DIVIDER4 ==== -->
    <section class="section-divider textdivider divider4">
      <div class="container">
        <h1>WE'VE CREATED THE NEW WAY OF MAKING THINGS HAPPEN</h1>
        <hr>
        <p>Now there's an easy and efficient way to bring together the people that you want when you want them. Eliminating group messages and bringing them into group orientation the LinkUp app allows you to add your contacts and seperate them into specific groups of your choosing, so you can find them easier later on. </p>
      </div><!-- container -->
    </section><!-- section -->
    
    <!-- ==== TEAM MEMBERS ==== -->
    <div class="container" id="team" name="team">
      <br>
      <div class="row white centered">
        <h1 class="centered">MEET OUR AWESOME TEAM</h1>
        <hr>
        <br>
        <br>
        <div class="col-lg-3 centered">
          <img class="img img-circle" src="assets/images/img/team/team01.jpg" height="120px" width="120px" alt="">
          <br>
          <h4><b>Blake Azuela</b></h4>
          <a href="#" class="icon icon-twitter"></a>
          <a href="#" class="icon icon-facebook"></a>
          <a href="#" class="icon icon-flickr"></a>
          <p>Some epic description of blake should go here making it a funny, yet some-what serious description of the main inspiration of this wonderful idea.</p>
        </div><!-- col-lg-3 -->
        
        <div class="col-lg-3 centered">
          <img class="img img-circle" src="assets/images/img/team/team02.jpg" height="120px" width="120px" alt="">
          <br>
          <h4><b>Josh Garcia</b></h4>
          <a href="#" class="icon icon-twitter"></a>
          <a href="#" class="icon icon-facebook"></a>
          <a href="#" class="icon icon-flickr"></a>
          <p>Joshie Poo also deserves a very epic description of himself because he can throw together one mean business plan, plus he has a cuteness even your momma would appreciate.</p>
        </div><!-- col-lg-3 -->
        
        <div class="col-lg-3 centered">
          <img class="img img-circle" src="assets/images/img/team/team03.jpg" height="120px" width="120px" alt="">
          <br>
          <h4><b>Alex Lucero</b></h4>
          <a href="#" class="icon icon-twitter"></a>
          <a href="#" class="icon icon-facebook"></a>
          <a href="#" class="icon icon-flickr"></a>
          <p>tAlex is just the youngun of the bunch, a sensible guy with the seriousness of Bugs Bunny. Watch out for this guy when its rabbit season.</p>
        </div><!-- col-lg-3 -->
        
        <div class="col-lg-3 centered">
          <img class="img img-circle" src="assets/images/img/team/team04.jpg" height="120px" width="120px" alt="">
          <br>
          <h4><b>JNick Williams</b></h4>
          <a href="#" class="icon icon-twitter"></a>
          <a href="#" class="icon icon-facebook"></a>
          <a href="#" class="icon icon-flickr"></a>
          <p>Nick's the brains of the operations, he also supports the ceiling with the top of his head. As a lead programmer he should have the most nerdy and serious description that doesnt really describe him very well at all, just to throw people off.</p>
        </div><!-- col-lg-3 -->        
      </div><!-- row -->
    </div><!-- container -->

    
    <!-- ==== SECTION DIVIDER6 ==== -->
    <section class="section-divider textdivider divider6">
      <div class="container">
        <h1>Handmade in Albuquerque, New Mexico</h1>
        <hr>
        <p>Some Address 987,</p>
        <p>Our contact number</p>
        <p><a class="icon icon-twitter" href="#"></a> | <a class="icon icon-facebook" href="#"></a></p>
      </div><!-- container -->
    </section><!-- section -->
    
    <div class="container" id="contact" name="contact">
      <div class="row">
      <br>
        <h1 class="centered">THANKS FOR VISITING US</h1>
        <hr>
        <br>
        <br>
        <div class="col-lg-4">
          <h3>Contact Information</h3>
          <p><span class="icon icon-home"></span> Some Address 987, NM<br/>
            <span class="icon icon-phone"></span> +34 9884 4893 <br/>
            <span class="icon icon-mobile"></span> +34 59855 9853 <br/>
            <span class="icon icon-envelop"></span> <a href="#"> Linkupabq@gmail.com</a> <br/>
            <span class="icon icon-twitter"></span> <a href="#"> @LinkUp </a> <br/>
            <span class="icon icon-facebook"></span> <a href="#"> LinkUp </a> <br/>
          </p>
        </div><!-- col -->
        
        <div class="col-lg-4">
          <h3>Newsletter</h3>
          <p>Register to our newsletter and be updated with the latests information regarding our services, offers and much more.</p>
          <p>
            <form class="form-horizontal" role="form">
              <div class="form-group">
                <label for="inputEmail1" class="col-lg-4 control-label"></label>
                <div class="col-lg-10">
                  <input type="email" class="form-control" id="inputEmail1" placeholder="Email">
                </div>
              </div>
              <div class="form-group">
                <label for="text1" class="col-lg-4 control-label"></label>
                <div class="col-lg-10">
                  <input type="text" class="form-control" id="text1" placeholder="Your Name">
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-10">
                  <button type="submit" class="btn btn-success">Sign in</button>
                </div>
              </div>
             </form><!-- form -->
          </p>
        </div><!-- col -->
        
        <div class="col-lg-4">
          <h3>Support Us</h3>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        </div><!-- col -->

      </div><!-- row -->
    
    </div><!-- container -->

    <div id="footerwrap">
      <div class="container">
        <h4>Created by LinkUp - Copyright 2014</h4>
      </div>
    </div>